# SEO settings
title: HP-Nunes
description: "Hadrien N Picq's portfolio of programming, writings, and thoughts"
keywords: "Hadrien Picq"
url: https://hpnunes.com/
baseurl: ""
show_excerpts: true # set to true to show excerpts on the homepage
# google_analytics: UA-133442052-1

# Author settings
author:
  name: HP-Nunes
  job: Programmatic Geographer
  bio: 
  thumb: /images/avatar2.jpg
  email: contact@hpnunes.com
  url: https://hpnunes.com/
  github: https://github.com/HP-Nunes
  twitter: https://twitter.com/geocuriosity
  linkedin: https://www.linkedin.com/in/hadnunpi/
  devpost: https://devpost.com/HadrienPicq

# Build settings
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
highlighter: rouge
plugins_dir: 
  - jekyll-seo-tag
  - jekyll-paginate-v2

# remote_theme: thelehhman/plainwhite-jekyll
# theme: plainwhite // will not host on GitHub Pages; only certain themes are supported: https://pages.github.com/themes/

pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Hadrien N Picq
  tagline: Data, Environment, Geography
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content


# navbar pages
# navbar:
#   - slug: about
#     title: About
#   - slug: icons
#     title: Icons
#   - slug: blog
#     title: Blog


  
