# SEO settings
title: HP-Nunes' personal site
description: "HP-Nunes's portfolio and blog; using the end2end jekyll template"
keywords: ""
url: https://hpnunes.com/
baseurl: ""

google_analytics: UA-133442052-1
# repo: http://github.com/nandomoreirame/end2end
# disqus_shortname: "nandothemes"
# disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: HP-Nunes
  job: Programmatic Geographer
  bio: 
  thumb: /images/avatar.jpg
  email: 
  url: https://hpnunes.com/
  github: https://github.com/HP-Nunes
  twitter: https://twitter.com/geocuriosity
  linkedin: https://www.linkedin.com/in/hadnunpi/

# Build settings
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

  
